-- BM: generic services + appointments (schema UM)
CREATE TABLE um.bm_service_item (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(300) NOT NULL,
  description CLOB,
  price NUMBER(18, 2) NOT NULL,
  duration_minutes NUMBER(10) NOT NULL,
  active NUMBER(1) DEFAULT 1 NOT NULL,
  metadata_json CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  created_by VARCHAR2(200),
  updated_by VARCHAR2(200)
);

CREATE TABLE um.bm_appointment (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  service_id NUMBER NOT NULL,
  title VARCHAR2(500) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  status VARCHAR2(20) NOT NULL,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  created_by VARCHAR2(200),
  updated_by VARCHAR2(200),
  CONSTRAINT fk_bm_appt_customer FOREIGN KEY (customer_id) REFERENCES um.kyc_customer (id),
  CONSTRAINT fk_bm_appt_service FOREIGN KEY (service_id) REFERENCES um.bm_service_item (id)
);

CREATE INDEX idx_bm_appt_customer_time ON um.bm_appointment (customer_id, start_time, end_time);
CREATE INDEX idx_bm_appt_start ON um.bm_appointment (start_time);
