-- Product photos + customer payment / sale tables (schema UM)
ALTER TABLE um.pm_product ADD (
  product_image_mime VARCHAR2(64),
  product_image_data BLOB
);

CREATE TABLE um.pm_customer_sale (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  total_amount NUMBER(18, 2) NOT NULL,
  status VARCHAR2(20) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_pm_sale_customer FOREIGN KEY (customer_id) REFERENCES um.kyc_customer(id)
);

CREATE TABLE um.pm_customer_sale_line (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  sale_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  product_name VARCHAR2(200) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(18, 2) NOT NULL,
  CONSTRAINT fk_pm_sale_line_sale FOREIGN KEY (sale_id) REFERENCES um.pm_customer_sale(id) ON DELETE CASCADE,
  CONSTRAINT fk_pm_sale_line_product FOREIGN KEY (product_id) REFERENCES um.pm_product(id)
);


CREATE SEQUENCE um_pm_customer_sale_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE um_pm_customer_sale_line_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
|
CREATE OR REPLACE TRIGGER um.pm_customer_sale_trigger
BEFORE INSERT ON um.pm_customer_sale
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT um_pm_customer_sale_seq.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER um.pm_customer_sale_line_trigger
BEFORE INSERT ON um.pm_customer_sale_line
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT um_pm_customer_sale_line_seq.NEXTVAL
        INTO :NEW.id
        FROM dual;
    END IF;
END;
/