-- UM: Relax UM_WORKFLOW_API_ENDPOINT uniqueness (allow multiple mutating paths per menu+action),
-- then seed mutating gateway paths for maker/checker replay (Oracle, idempotent).

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT DROP CONSTRAINT UK_WF_EP_MENU_ACT';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT ADD CONSTRAINT UK_WF_EP_SVC_PATH UNIQUE (SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2261 AND SQLCODE != -2264 THEN RAISE; END IF;
END;
/

-- PM products + BM products + sales (menu /pm/products)
INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'pm', 'POST', '/pm/product/add', m.ID, '/pm/products', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'pm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/pm/product/add');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'pm', 'POST', '/pm/product/update', m.ID, '/pm/products', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'pm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/pm/product/update');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'pm', 'POST', '/pm/product/delete', m.ID, '/pm/products', 'DELETE', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'pm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/pm/product/delete');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'pm', 'POST', '/pm/sale/checkout', m.ID, '/pm/products', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'pm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/pm/sale/checkout');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/product/add', m.ID, '/pm/products', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/product/add');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/product/update', m.ID, '/pm/products', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/product/update');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/product/delete', m.ID, '/pm/products', 'DELETE', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/product/delete');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/sale/checkout', m.ID, '/pm/products', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/pm/products' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/sale/checkout');

-- BM appointments
INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/appointments/add', m.ID, '/bm/appointments', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/appointments' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/appointments/add');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/appointments/update', m.ID, '/bm/appointments', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/appointments' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/appointments/update');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/appointments/cancel', m.ID, '/bm/appointments', 'DELETE', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/appointments' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/appointments/cancel');

-- BM services
INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/service-item/add', m.ID, '/bm/services', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/services' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/service-item/add');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/service-item/update', m.ID, '/bm/services', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/services' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/service-item/update');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'bm', 'POST', '/bm/service-item/deactivate', m.ID, '/bm/services', 'DELETE', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/bm/services' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'bm' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/bm/service-item/deactivate');

-- KYC customers
INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'kyc', 'POST', '/kyc/customer/add', m.ID, '/kyc/customers', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/kyc/customers' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'kyc' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/kyc/customer/add');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'kyc', 'POST', '/kyc/customer/update', m.ID, '/kyc/customers', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/kyc/customers' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'kyc' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/kyc/customer/update');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'kyc', 'POST', '/kyc/customer/delete', m.ID, '/kyc/customers', 'DELETE', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/kyc/customers' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'kyc' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/kyc/customer/delete');

-- Broadcast
INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'broadcast', 'POST', '/broadcast/message/create', m.ID, '/broadcast', 'ADD', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/broadcast' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'broadcast' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/broadcast/message/create');

INSERT INTO UM.UM_WORKFLOW_API_ENDPOINT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, MENU_ID, SCREEN_ROUTE, ACTION_CODE, PRIORITY, IS_ACTIVE, CREATED_AT)
SELECT UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, 'broadcast', 'POST', '/broadcast/message/send', m.ID, '/broadcast', 'EDIT', 10, 1, SYSTIMESTAMP
FROM UM.UM_MENUS m WHERE m.ROUTE = '/broadcast' AND ROWNUM = 1
AND NOT EXISTS (SELECT 1 FROM UM.UM_WORKFLOW_API_ENDPOINT e WHERE e.SERVICE_KEY = 'broadcast' AND e.HTTP_METHOD = 'POST' AND e.PATH_ANT_PATTERN = '/broadcast/message/send');

COMMIT;
