-- =============================================================================
-- Workflow Engine v2: pipeline type, role run restrictions, extended step types
-- Run after: patch-um-workflow-engine-oracle.sql
-- =============================================================================

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_DEFINITION ADD (
    WORKFLOW_TYPE VARCHAR2(40) DEFAULT ''ACTION_PIPELINE'' NOT NULL,
    ROLE_RESTRICTED NUMBER(1) DEFAULT 0 NOT NULL,
    ALLOW_CHILD_ROLE_INHERIT NUMBER(1) DEFAULT 0 NOT NULL,
    ROLE_CODES_JSON CLOB
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE UM.UM_WORKFLOW_DEFINITION ADD CONSTRAINT CK_UM_WF_DEF_TYPE CHECK (
      WORKFLOW_TYPE IN ('ACTION_PIPELINE', 'APPROVAL_GATEWAY', 'NOTIFICATION_ONLY', 'CUSTOM')
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2264, -2275, -2261) THEN RAISE; END IF; END;
/

-- Widen step types (drop/recreate check if present)
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_STEP DROP CONSTRAINT CK_UM_WF_STEP_TYPE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2443 THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE UM.UM_WORKFLOW_STEP ADD CONSTRAINT CK_UM_WF_STEP_TYPE CHECK (STEP_TYPE IN (
      'APPROVAL', 'NOTIFICATION', 'HTTP_TASK', 'HTTP_POLL', 'SYSTEM'
    ))
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2264, -2275) THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_STEP ADD (
    TASK_KEY VARCHAR2(80),
    DISPLAY_LABEL VARCHAR2(200)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/
