-- =============================================================================
-- Unify workflow triggers into UM_WORKFLOW_API_ENDPOINT (single catalog).
-- Migrates UM_WORKFLOW_ACTION rows as DOMAIN triggers; pipelines use EP:{id} codes.
-- Run after: patch-um-workflow-api-endpoints-oracle.sql, patch-um-workflow-engine-oracle.sql
-- =============================================================================

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT ADD (
    ENGINE_ACTION_CODE VARCHAR2(80),
    DISPLAY_NAME VARCHAR2(200),
    DESCRIPTION VARCHAR2(1000),
    TRIGGER_KIND VARCHAR2(30) DEFAULT ''IMMEDIATE'' NOT NULL,
    TRIGGER_SOURCE VARCHAR2(20) DEFAULT ''HTTP'' NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT ADD CONSTRAINT CK_WF_EP_TRIG_SRC CHECK (
      TRIGGER_SOURCE IN ('HTTP', 'DOMAIN')
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2264, -2275, -2261) THEN RAISE; END IF; END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT ADD CONSTRAINT CK_WF_EP_TRIG_KIND CHECK (
      TRIGGER_KIND IN ('IMMEDIATE', 'AFTER_APPROVAL', 'SCHEDULED', 'MANUAL')
    )
  ]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-2264, -2275, -2261) THEN RAISE; END IF; END;
/

-- Allow DOMAIN rows without a real HTTP path (internal trigger key only).
-- ORA-01451 = column is already nullable (safe to ignore on re-run).
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_API_ENDPOINT MODIFY (PATH_ANT_PATTERN NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE NOT IN (-1442, -1451) THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UK_WF_EP_ENGINE_ACTION ON UM.UM_WORKFLOW_API_ENDPOINT (ENGINE_ACTION_CODE)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF; END;
/

-- Copy legacy domain actions into endpoint catalog (skip if table already dropped).
DECLARE
  v_has_legacy NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_has_legacy
  FROM all_tables
  WHERE owner = 'UM' AND table_name = 'UM_WORKFLOW_ACTION';

  IF v_has_legacy > 0 THEN
    MERGE INTO UM.UM_WORKFLOW_API_ENDPOINT t
    USING (
      SELECT ACTION_CODE AS ENGINE_ACTION_CODE,
             DISPLAY_NAME,
             DESCRIPTION,
             MODULE_KEY AS SERVICE_KEY,
             TRIGGER_KIND,
             'DOMAIN' AS TRIGGER_SOURCE,
             '/um/workflow-engine' AS SCREEN_ROUTE,
             'EVENT' AS ACTION_CODE,
             '/um/internal/trigger/' || ACTION_CODE AS PATH_ANT_PATTERN,
             'INTERNAL' AS HTTP_METHOD
      FROM UM.UM_WORKFLOW_ACTION
      WHERE IS_ACTIVE = 1
    ) s ON (t.ENGINE_ACTION_CODE = s.ENGINE_ACTION_CODE)
    WHEN NOT MATCHED THEN
      INSERT (ID, SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN, SCREEN_ROUTE, ACTION_CODE,
              PRIORITY, IS_ACTIVE, CREATED_AT, ENGINE_ACTION_CODE, DISPLAY_NAME, DESCRIPTION,
              TRIGGER_KIND, TRIGGER_SOURCE)
      VALUES (UM.S_UM_WORKFLOW_API_ENDPOINT.NEXTVAL, s.SERVICE_KEY, s.HTTP_METHOD, s.PATH_ANT_PATTERN,
              s.SCREEN_ROUTE, s.ACTION_CODE, 5, 1, SYSTIMESTAMP, s.ENGINE_ACTION_CODE, s.DISPLAY_NAME,
              s.DESCRIPTION, s.TRIGGER_KIND, s.TRIGGER_SOURCE);
  END IF;
END;
/

-- Back-fill display names on existing HTTP rows from screen + permission verb.
UPDATE UM.UM_WORKFLOW_API_ENDPOINT e
SET DISPLAY_NAME = NVL(e.DISPLAY_NAME, e.SCREEN_ROUTE || ' · ' || e.ACTION_CODE),
    ENGINE_ACTION_CODE = NVL(e.ENGINE_ACTION_CODE, 'EP_' || e.ID),
    TRIGGER_SOURCE = NVL(TRIGGER_SOURCE, 'HTTP'),
    TRIGGER_KIND = NVL(TRIGGER_KIND, 'IMMEDIATE')
WHERE TRIGGER_SOURCE = 'HTTP' OR TRIGGER_SOURCE IS NULL;

-- Point pipelines at EP:{id} (canonical trigger key).
-- Oracle MERGE cannot UPDATE a column that appears in the ON clause (ORA-38104); join on ID instead.
MERGE INTO UM.UM_WORKFLOW_DEFINITION d
USING (
  SELECT defn.ID AS DEF_ID, 'EP:' || ep.ID AS NEW_CODE
  FROM UM.UM_WORKFLOW_DEFINITION defn
  INNER JOIN UM.UM_WORKFLOW_API_ENDPOINT ep ON ep.ENGINE_ACTION_CODE = defn.ACTION_CODE
  WHERE ep.ENGINE_ACTION_CODE IS NOT NULL
    AND defn.ACTION_CODE NOT LIKE 'EP:%'
) m ON (d.ID = m.DEF_ID)
WHEN MATCHED THEN UPDATE SET d.ACTION_CODE = m.NEW_CODE;

COMMIT;

-- Next (optional cleanup): patch-um-workflow-action-drop-oracle.sql
