-- UM: HTTP workflow endpoint registry + captured replay columns (Oracle, idempotent fragments).
-- Links gateway-visible paths (Ant patterns) to menu screen routes + permission verbs for maker/checker deferral (202) and approve-time replay.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM all_sequences WHERE sequence_owner = 'UM' AND sequence_name = 'S_UM_WORKFLOW_API_ENDPOINT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE UM.S_UM_WORKFLOW_API_ENDPOINT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM all_tables WHERE owner = 'UM' AND table_name = 'UM_WORKFLOW_API_ENDPOINT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE UM.UM_WORKFLOW_API_ENDPOINT (
      ID NUMBER(19) NOT NULL,
      SERVICE_KEY VARCHAR2(32) NOT NULL,
      HTTP_METHOD VARCHAR2(16) NOT NULL,
      PATH_ANT_PATTERN VARCHAR2(500),
      MENU_ID NUMBER(19),
      SCREEN_ROUTE VARCHAR2(400) NOT NULL,
      ACTION_CODE VARCHAR2(40) NOT NULL,
      PRIORITY NUMBER(10) DEFAULT 0 NOT NULL,
      IS_ACTIVE NUMBER(1) DEFAULT 0 NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_UM_WORKFLOW_API_ENDPOINT PRIMARY KEY (ID),
      CONSTRAINT FK_WF_EP_MENU FOREIGN KEY (MENU_ID) REFERENCES UM.UM_MENUS (ID),
      CONSTRAINT UK_WF_EP_SVC_PATH UNIQUE (SERVICE_KEY, HTTP_METHOD, PATH_ANT_PATTERN)
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_WF_EP_ACTIVE ON UM.UM_WORKFLOW_API_ENDPOINT (IS_ACTIVE, PRIORITY DESC)';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (ENDPOINT_ID NUMBER(19))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (CAPTURED_HTTP_METHOD VARCHAR2(16))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (CAPTURED_HTTP_PATH VARCHAR2(4000))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (CAPTURED_HTTP_QUERY VARCHAR2(4000))';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (CAPTURED_HEADERS_JSON CLOB)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_WORKFLOW_INSTANCE ADD (CAPTURED_BODY CLOB)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
