-- Run as Oracle user UM if SELECT on UM.UM_USER fails with invalid identifier for MOBILE_NUMBER, STATUS, or CREATED_AT.
-- Each block ignores ORA-01430 (column already exists).

BEGIN EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_USER ADD (MOBILE_NUMBER VARCHAR2(40 CHAR))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -01430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_USER ADD (STATUS VARCHAR2(50 CHAR))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -01430 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER TABLE UM.UM_USER ADD (CREATED_AT TIMESTAMP(6))'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -01430 THEN RAISE; END IF; END;
/
