-- Travel business extensions: destinations, trip requests, column extensions
-- Run as UM user after travel-schema-oracle.sql

CREATE TABLE um.travel_destination (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  name VARCHAR2(300) NOT NULL,
  country VARCHAR2(128),
  region VARCHAR2(128),
  visa_requirements CLOB,
  health_requirements CLOB,
  high_season_notes CLOB,
  low_season_notes CLOB,
  travel_warnings CLOB,
  risk_level VARCHAR2(32),
  travel_advisory CLOB,
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_travel_dest_business FOREIGN KEY (business_id) REFERENCES um.um_business (id)
);

CREATE TABLE um.travel_trip_request (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  client_id NUMBER(19) NOT NULL,
  destination_id NUMBER(19),
  destination_name VARCHAR2(300),
  departure_date DATE,
  return_date DATE,
  budget_amount NUMBER(18, 2),
  currency VARCHAR2(3) DEFAULT 'USD',
  traveler_count NUMBER(10),
  traveler_details CLOB,
  status VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  quoted_amount NUMBER(18, 2),
  notes CLOB,
  assigned_to VARCHAR2(200),
  booking_id NUMBER(19),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT fk_travel_trip_req_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_trip_req_client FOREIGN KEY (client_id) REFERENCES um.travel_client (id),
  CONSTRAINT fk_travel_trip_req_dest FOREIGN KEY (destination_id) REFERENCES um.travel_destination (id),
  CONSTRAINT fk_travel_trip_req_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

ALTER TABLE um.travel_client ADD (travel_profile_json CLOB);

ALTER TABLE um.travel_package ADD (
  destinations_json CLOB,
  addons_json CLOB,
  max_capacity_per_day NUMBER(10)
);

ALTER TABLE um.travel_booking ADD (
  timeline_stage VARCHAR2(32),
  approval_status VARCHAR2(32),
  payment_schedule_json CLOB,
  requires_approval NUMBER(1)
);

ALTER TABLE um.travel_supplier ADD (
  contracts_json CLOB,
  commission_notes CLOB,
  rate_table_notes CLOB
);

CREATE INDEX idx_travel_destination_biz ON um.travel_destination (business_id);
CREATE INDEX idx_travel_trip_request_biz ON um.travel_trip_request (business_id);

INSERT INTO UM.UM_MENUS (ID, APPLICATION_ID, PARENT_ID, NAME, ROUTE, ICON, IS_ACTIVE, ALLOWED_ROLES)
SELECT UM.S_UM_MENUS.NEXTVAL, a.ID, NULL, 'Destinations', '/travel/destinations', 'public', 1, NULL
FROM UM.UM_APPLICATIONS a
WHERE a.IS_ACTIVE = 1 AND UPPER(TRIM(a.NAME)) IN ('TRAVEL', 'TRAVEL AGENCY')
  AND NOT EXISTS (SELECT 1 FROM UM.UM_MENUS m WHERE m.ROUTE = '/travel/destinations');

INSERT INTO UM.UM_MENUS (ID, APPLICATION_ID, PARENT_ID, NAME, ROUTE, ICON, IS_ACTIVE, ALLOWED_ROLES)
SELECT UM.S_UM_MENUS.NEXTVAL, a.ID, NULL, 'Trip requests', '/travel/trip-requests', 'request_quote', 1, NULL
FROM UM.UM_APPLICATIONS a
WHERE a.IS_ACTIVE = 1 AND UPPER(TRIM(a.NAME)) IN ('TRAVEL', 'TRAVEL AGENCY')
  AND NOT EXISTS (SELECT 1 FROM UM.UM_MENUS m WHERE m.ROUTE = '/travel/trip-requests');

COMMIT;
