-- Travel agency module (schema UM, travel_* tables)
-- Run as UM user. All tenant tables require business_id.

-- NUMBER(19) ids with identity (JPA GenerationType.IDENTITY)

CREATE TABLE um.travel_client (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  full_name VARCHAR2(300) NOT NULL,
  email VARCHAR2(320),
  phone VARCHAR2(40),
  passport_no VARCHAR2(64),
  notes CLOB,
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  created_by VARCHAR2(200),
  updated_by VARCHAR2(200),
  CONSTRAINT fk_travel_client_business FOREIGN KEY (business_id) REFERENCES um.um_business (id)
);

CREATE TABLE um.travel_package (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  code VARCHAR2(64),
  name VARCHAR2(300) NOT NULL,
  description CLOB,
  inclusions CLOB,
  exclusions CLOB,
  itinerary_json CLOB,
  media_json CLOB,
  destination VARCHAR2(200),
  duration_days NUMBER(10),
  base_price NUMBER(18, 2) NOT NULL,
  currency VARCHAR2(3) DEFAULT 'USD',
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  created_by VARCHAR2(200),
  updated_by VARCHAR2(200),
  CONSTRAINT fk_travel_package_business FOREIGN KEY (business_id) REFERENCES um.um_business (id)
);

CREATE TABLE um.travel_booking (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  client_id NUMBER(19) NOT NULL,
  package_id NUMBER(19),
  reference_no VARCHAR2(64),
  status VARCHAR2(32) DEFAULT 'DRAFT' NOT NULL,
  departure_date DATE,
  return_date DATE,
  total_amount NUMBER(18, 2),
  currency VARCHAR2(3) DEFAULT 'USD',
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  created_by VARCHAR2(200),
  updated_by VARCHAR2(200),
  CONSTRAINT fk_travel_booking_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_booking_client FOREIGN KEY (client_id) REFERENCES um.travel_client (id),
  CONSTRAINT fk_travel_booking_package FOREIGN KEY (package_id) REFERENCES um.travel_package (id)
);

CREATE TABLE um.travel_booking_passenger (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  booking_id NUMBER(19) NOT NULL,
  full_name VARCHAR2(300) NOT NULL,
  passport_no VARCHAR2(64),
  date_of_birth DATE,
  nationality VARCHAR2(64),
  seat_preference VARCHAR2(32),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_travel_passenger_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_passenger_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

CREATE TABLE um.travel_booking_component (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  booking_id NUMBER(19) NOT NULL,
  component_type VARCHAR2(32) NOT NULL,
  description VARCHAR2(500),
  supplier_id NUMBER(19),
  amount NUMBER(18, 2),
  status VARCHAR2(32),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_travel_component_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_component_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

CREATE TABLE um.travel_visa_application (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  client_id NUMBER(19) NOT NULL,
  booking_id NUMBER(19),
  country VARCHAR2(64) NOT NULL,
  visa_type VARCHAR2(64),
  status VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  submitted_at TIMESTAMP,
  decision_at TIMESTAMP,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP,
  CONSTRAINT fk_travel_visa_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_visa_client FOREIGN KEY (client_id) REFERENCES um.travel_client (id),
  CONSTRAINT fk_travel_visa_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

CREATE TABLE um.travel_document (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  client_id NUMBER(19),
  booking_id NUMBER(19),
  doc_type VARCHAR2(64) NOT NULL,
  file_name VARCHAR2(300),
  storage_ref VARCHAR2(500),
  uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  uploaded_by VARCHAR2(200),
  CONSTRAINT fk_travel_document_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_document_client FOREIGN KEY (client_id) REFERENCES um.travel_client (id),
  CONSTRAINT fk_travel_document_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

CREATE TABLE um.travel_supplier (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  name VARCHAR2(300) NOT NULL,
  supplier_type VARCHAR2(64),
  contact_email VARCHAR2(320),
  contact_phone VARCHAR2(40),
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_travel_supplier_business FOREIGN KEY (business_id) REFERENCES um.um_business (id)
);

CREATE TABLE um.travel_invoice (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  booking_id NUMBER(19) NOT NULL,
  invoice_no VARCHAR2(64),
  amount NUMBER(18, 2) NOT NULL,
  currency VARCHAR2(3) DEFAULT 'USD',
  status VARCHAR2(32) DEFAULT 'OPEN' NOT NULL,
  issued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  due_at TIMESTAMP,
  CONSTRAINT fk_travel_invoice_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_invoice_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

CREATE TABLE um.travel_payment (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  invoice_id NUMBER(19) NOT NULL,
  amount NUMBER(18, 2) NOT NULL,
  payment_method VARCHAR2(32),
  paid_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  reference_no VARCHAR2(128),
  CONSTRAINT fk_travel_payment_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_payment_invoice FOREIGN KEY (invoice_id) REFERENCES um.travel_invoice (id)
);

CREATE TABLE um.travel_commission_rule (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  name VARCHAR2(200) NOT NULL,
  rule_type VARCHAR2(32) NOT NULL,
  rate_percent NUMBER(8, 4),
  flat_amount NUMBER(18, 2),
  active NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_travel_comm_rule_business FOREIGN KEY (business_id) REFERENCES um.um_business (id)
);

CREATE TABLE um.travel_follow_up (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  client_id NUMBER(19),
  booking_id NUMBER(19),
  subject VARCHAR2(300) NOT NULL,
  due_at TIMESTAMP,
  status VARCHAR2(32) DEFAULT 'OPEN' NOT NULL,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  assigned_to VARCHAR2(200),
  CONSTRAINT fk_travel_follow_up_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_follow_up_client FOREIGN KEY (client_id) REFERENCES um.travel_client (id),
  CONSTRAINT fk_travel_follow_up_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id)
);

-- Consultant commission ledger (doc 9.5)
CREATE TABLE um.travel_consultant_commission (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  business_id NUMBER(19) NOT NULL,
  booking_id NUMBER(19) NOT NULL,
  consultant_user_id NUMBER(19),
  commission_rule_id NUMBER(19),
  base_amount NUMBER(18, 2) NOT NULL,
  commission_amount NUMBER(18, 2) NOT NULL,
  status VARCHAR2(32) DEFAULT 'ACCRUED' NOT NULL,
  accrued_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  paid_at TIMESTAMP,
  notes VARCHAR2(500),
  CONSTRAINT fk_travel_cons_comm_business FOREIGN KEY (business_id) REFERENCES um.um_business (id),
  CONSTRAINT fk_travel_cons_comm_booking FOREIGN KEY (booking_id) REFERENCES um.travel_booking (id),
  CONSTRAINT fk_travel_cons_comm_rule FOREIGN KEY (commission_rule_id) REFERENCES um.travel_commission_rule (id)
);

CREATE INDEX idx_travel_client_biz ON um.travel_client (business_id);
CREATE INDEX idx_travel_package_biz ON um.travel_package (business_id);
CREATE INDEX idx_travel_booking_biz ON um.travel_booking (business_id);
CREATE INDEX idx_travel_booking_client ON um.travel_booking (business_id, client_id);
CREATE INDEX idx_travel_visa_biz ON um.travel_visa_application (business_id);
CREATE INDEX idx_travel_invoice_biz ON um.travel_invoice (business_id);
CREATE INDEX idx_travel_follow_up_biz ON um.travel_follow_up (business_id);
CREATE INDEX idx_travel_cons_comm_biz ON um.travel_consultant_commission (business_id);
